some code improvements

diff --git a/post-merge/post-merge_checkinstall b/post-merge/post-merge_checkinstall
--- a/post-merge/post-merge_checkinstall
+++ b/post-merge/post-merge_checkinstall
@@ -1,5 +1,8 @@
 #!/bin/bash
 #
+# Thanks to Felipe Eduardo Sanchez Diaz Duran <izto@asic-linux.com.mx>, the
+# author of checkinstall for the many ideas
+#
 # TODO JSON (http://www.jsoneditoronline.org/) Konfiguration berücksichtigen, jeweils in ".git/hooks/postmergerc"
 # z.B.
 #	{
@@ -9,10 +12,79 @@
 #	  "checkinstall": "--exclude /usr/local/lib/python2.7/dist-packages/easy-install.pth"
 #	}
 
+# Trap the INT signal (ctrl-c, for example)
+trap trapint 2
+
 red="\e[0;31m"
 green="\e[0;32m"
 yellow="\e[0;33m"
 NC="\e[0m" # No Color
+
+# Enable alias expansion in command substitution
+shopt -s expand_aliases
+
+# Vefify that we have gettext available
+gettext "Bye." &> /dev/null
+if [ $? -gt 0 ]; then
+  alias ck_gettext="echo -e"
+else
+  alias ck_gettext="gettext -s --"
+fi
+
+## echo with newline at the end
+function echog() {
+  local format="$1"
+  shift
+  printf -- "$(ck_gettext "$format")\n" "$@" >&2
+}
+
+## echo with NO newline at the end
+function   echogn() {
+  local format="$1"
+  shift
+  printf -- "$(ck_gettext "$format")" "$@" >&2
+}
+
+# Prints OK or FAILED! depending on previous command return value
+function okfail () {
+  if [ $? -gt 0 ]; then
+    logError "Es trat ein Fehler auf. Bitte vorhergehende Ausgaben überprüfen. Breche ab."
+    return 1
+  else
+    logInfo "OK"
+    return 0
+  fi
+}
+
+function logInfo () {
+  green="\e[0;32m"
+  echog "${green}$1${NC}"
+}
+
+function logWarn () {
+  yellow="\e[0;33m"
+  echog "${yellow}$1${NC}"
+}
+
+function logError () {
+  red="\e[0;31m"
+  echog "${red}$1${NC}"
+}
+
+function trapint {
+  echo
+  echo
+  echog "$(basename "$0") SIGINT received"
+  cleanup
+}
+
+function cleanup {
+  echogn "Cleaning up..."
+  okfail
+  echog "Bye."
+  echo
+  exit 1
+}
 
 autogenParam=""
 configureParam=""
@@ -20,20 +92,20 @@ checkinstallParam=""
 
 if [ -f ".git/hooks/postmergerc" ]
 then
-  echo -e "${yellow}.git/hooks/postmergerc${NC} gefunden"
+  logInfo "\".git/hooks/postmergerc\" gefunden"
   
   autogenParam=$(jq '.autogen' .git/hooks/postmergerc | tr -d "\"")
-  if [ "$autogenParam" != "" ]; then echo -e "Zusätzliche Parameter autogen"; echo -e "\t${green}$autogenParam${NC}"; fi
+  if [ "$autogenParam" != "" ]; then echog "Zusätzliche Parameter autogen"; echog "\t${green}$autogenParam${NC}"; fi
 
   configureParam=$(jq '.configure' .git/hooks/postmergerc | tr -d "\"")
-  if [ "$configureParam" != "" ]; then echo -e "Zusätzliche Parameter configure"; echo -e "\t${green}$configureParam${NC}"; fi
+  if [ "$configureParam" != "" ]; then echog "Zusätzliche Parameter configure"; echog "\t${green}$configureParam${NC}"; fi
   
   makeParam=$(jq '.make' .git/hooks/postmergerc | tr -d "\"")
-  if [ "$makeParam" != "" ]; then echo -e "Zusätzliche Parameter make"; echo -e "\t${green}$makeParam${NC}"; fi
+  if [ "$makeParam" != "" ]; then echog "Zusätzliche Parameter make"; echog "\t${green}$makeParam${NC}"; fi
 
   checkinstallParam=$(jq '.checkinstall' .git/hooks/postmergerc | tr -d "\"")
-  if [ "$checkinstallParam" != "" ]; then echo -e "Zusätzliche Parameter checkinstall"; echo -e "\t${green}$checkinstallParam${NC}"; fi
-  
+  if [ "$checkinstallParam" != "" ]; then echog "Zusätzliche Parameter checkinstall"; echog "\t${green}$checkinstallParam${NC}"; fi
+  echo
 fi
 
 # GIT
@@ -49,12 +121,13 @@ isGitHub=$(echo "$responseGitHub" | jq '.errors <= 0')
 
 if [ "$isGitHub" == "true" ]
 then
-  echo -e "${green}Gehostet auf GitHub, API kann verwendet werden.${NC}"
+  logInfo "Gehostet auf GitHub, API kann verwendet werden."
+  echo
 fi
 
 if [ "$(command -v easy_install)" != "" ]
 then
-  echo -e "${yellow}Das Programm \"easy_install\" aus dem Paket \"python-setuptools\" ist installiert. Das kann in Verbindung mit dem hier verwendeten \"checkinstall\" zu Problemen führen.${NC}"
+  logWarn "Das Programm \"easy_install\" aus dem Paket \"python-setuptools\" ist installiert. Das kann in Verbindung mit dem hier verwendeten \"checkinstall\" zu Problemen führen."
 fi
 
 exec < /dev/tty
@@ -73,7 +146,7 @@ done
 
 if [ -f description-pak ]
 then
-  echo -e "Lösche ${yellow}description-pak${NC}"
+  echog "Lösche ${yellow}description-pak${NC}"
   if [ -w description-pak ]
   then
     rm description-pak
@@ -86,35 +159,23 @@ fi
 
 if [ -f autogen.sh ]
 then
-  echo -e "Starte ${green}autogen.sh${NC}"
+  logInfo "Starte autogen.sh"
   ./autogen.sh $autogenParam
-  OUT=$?
-  if [ $OUT -ne 0 ];then
-    echo -e "${red}Es trat ein Fehler auf. Bitte vorhergehende Ausgaben überprüfen. Breche ab.${NC}"
-    exit
-  fi
+  okfail; [ $? -gt 0 ] && exit 1
 fi
 
 if [ -f configure ]
 then
-  echo -e "Starte ${green}configure${NC}"
+  logInfo "Starte configure"
   ./configure $configureParam
-  OUT=$?
-  if [ $OUT -ne 0 ];then
-    echo -e "${red}Es trat ein Fehler auf. Bitte vorhergehende Ausgaben überprüfen. Breche ab.${NC}"
-    exit
-  fi
+  okfail; [ $? -gt 0 ] && exit 1
 fi
 
 if [ -f "Makefile" ]
 then
-  echo -e "Starte ${green}make${NC}"
+  logInfo "Starte make"
   make $makeParam
-  OUT=$?
-  if [ $OUT -ne 0 ];then
-    echo -e "${red}Es trat ein Fehler auf. Bitte vorhergehende Ausgaben überprüfen. Breche ab.${NC}"
-    exit
-  fi
+  okfail; [ $? -gt 0 ] && exit 1
 fi
 
 
@@ -136,13 +197,13 @@ fi
 
 if [ -f "debian/changelog" ]
 then
-  echo -e "Verwende: ${green}debian/changelog${NC}"
+  echog "Verwende: ${green}debian/changelog${NC}"
   if [ "$version" == "" ]; then version=$(head -1 "debian/changelog" | gawk -F " " '{print $2}' |  tr -d "()"); fi
 fi
 
 if [ -f "debian/control" ]
 then
-  echo -e "Verwende: ${green}debian/control${NC}"
+  echog "Verwende: ${green}debian/control${NC}"
   if [ "$architecture" == "" ]; then architecture=$(grep '^ *Architecture *' "debian/control" | gawk -F ":" '{print $2}' |  tr -d " "); fi
   if [ "$requires" == "" ]; then requires=$(grep '^ *Depends *' "debian/control" | gawk -F ":" '{print $2}' |  tr -d " "); fi
   if [ "$maintainer" == "" ]; then maintainer=$(grep '^ *Maintainer *' "debian/control" | gawk -F ":" '{print $2}' | sed -e 's/^ *//' -e 's/ *$//'); fi
@@ -152,60 +213,60 @@ fi
 
 if [ -f "Makefile" ]
 then
-  echo -e "Verwende: ${green}Makefile${NC}"
+  echog "Verwende: ${green}Makefile${NC}"
   if [ "$version" == "" ]; then version=$(grep '^ *PACKAGE_VERSION *= *' Makefile | gawk -F "=" '{print $2}' |  tr -d " "); fi
-  if [ "$version" != "" ]; then echo -e "\tVersion: ${green}$version${NC}"; fi
+  if [ "$version" != "" ]; then echog "\tVersion: ${green}$version${NC}"; fi
 fi
 
 if [ -f "$name.spec" ]
 then
-  echo -e "Verwende: ${green}$name.spec${NC}"
+  echog "Verwende: ${green}$name.spec${NC}"
   if [ "$license" == "" ]; then license=$(grep '^ *License *' "$name.spec" | gawk -F ":" '{print $2}' |  tr -d " "); fi
-  if [ "$license" != "" ]; then echo -e "\tLicense: ${green}$license${NC}"; fi
+  if [ "$license" != "" ]; then echog "\tLicense: ${green}$license${NC}"; fi
   
   if [ "$group" == "" ]; then group=$(grep '^ *Group *' "$name.spec" | gawk -F ":" '{print $2}' |  tr -d " "); fi
-  if [ "$group" != "" ]; then echo -e "\tGroup: ${green}$group${NC}"; fi
+  if [ "$group" != "" ]; then echog "\tGroup: ${green}$group${NC}"; fi
   
   if [ "$summary" == "" ]; then summary=$(grep '^ *Summary *' "$name.spec" | gawk -F ":" '{print $2}' | sed -e 's/^ *//' -e 's/ *$//'); echo "$summary" > description-pak; fi
-  if [ "$summary" != "" ]; then echo -e "\tSummary: ${green}$summary${NC}"; fi
+  if [ "$summary" != "" ]; then echog "\tSummary: ${green}$summary${NC}"; fi
   
   if [ "$requires" == "" ]; then requires=$(grep '^ *Requires *' "$name.spec" | gawk -F ":" '{print $2}' |  tr -d " " | tr '\n' ',' | sed -e 's/^,*//' -e 's/,*$//'); fi
-  if [ "$requires" != "" ]; then echo -e "\tRequires: ${green}$requires${NC}"; fi
+  if [ "$requires" != "" ]; then echog "\tRequires: ${green}$requires${NC}"; fi
 fi
 
 if [ -f "setup.py" ]
 then
   if [ ! -x "setup.py" ]
   then
-    echo -e "${red}setup.py ist nicht ausführbar -> Abbruch.${NC}"
+    echog "${red}setup.py ist nicht ausführbar -> Abbruch.${NC}"
     exit
   else
-    echo -e "Verwende: ${green}setup.py${NC}"
+    echog "Verwende: ${green}setup.py${NC}"
     if [ "$maintainer" == "" ]; then maintainer=$(./setup.py --author); fi
-    if [ "$maintainer" != "" ]; then echo -e "\tMaintainer: ${green}$maintainer${NC}"; fi
+    if [ "$maintainer" != "" ]; then echog "\tMaintainer: ${green}$maintainer${NC}"; fi
     
     if [ "$maintainermail" == "" ]; then maintainermail=$(./setup.py --author-email); fi
-    if [ "$maintainermail" != "" ]; then echo -e "\tMaintainer eMail: ${green}$maintainermail${NC}"; fi
+    if [ "$maintainermail" != "" ]; then echog "\tMaintainer eMail: ${green}$maintainermail${NC}"; fi
     
     if [ "$version" == "" ]; then version=$(./setup.py --version); fi
-    if [ "$version" != "" ]; then echo -e "\tVersion: ${green}$version${NC}"; fi
+    if [ "$version" != "" ]; then echog "\tVersion: ${green}$version${NC}"; fi
     
     if [ "$license" == "" ]; then license=$(./setup.py --license); fi
-    if [ "$license" != "" ]; then echo -e "\tLicense: ${green}$license${NC}"; fi
+    if [ "$license" != "" ]; then echog "\tLicense: ${green}$license${NC}"; fi
     
     if [ "$requires" == "" ]; then requires=$(./setup.py --requires); fi
-    if [ "$requires" != "" ]; then echo -e "\tRequires: ${green}$requires${NC}"; fi
+    if [ "$requires" != "" ]; then echog "\tRequires: ${green}$requires${NC}"; fi
     
     if [ "$summary" == "" ]; then summary=$(./setup.py --description); echo "$summary" > description-pak; fi
-    if [ "$summary" != "" ]; then echo -e "\tSummary: ${green}$summary${NC}"; fi
+    if [ "$summary" != "" ]; then echog "\tSummary: ${green}$summary${NC}"; fi
   fi
 fi
 
 if [ "$isGitHub" == "true" ]
 then
-  echo -e "Verwende: ${green}GitHub-API${NC}"
+  echog "Verwende: ${green}GitHub-API${NC}"
   if [ "$summary" == "" ]; then summary=$(echo "$responseGitHub" | jq '.items[].description' | sed -e 's/^"*//' -e 's/"*$//'); echo "$summary" > description-pak; fi
-  if [ "$summary" != "" ]; then echo -e "\tSummary: ${green}$summary${NC}"; fi
+  if [ "$summary" != "" ]; then echog "\tSummary: ${green}$summary${NC}"; fi
 fi
 
 if [ "$sourceHtmlUrl" == "" ]
@@ -215,14 +276,15 @@ fi
 
 if [ -f "setup.py" ]
 then
+  echo
+  echog "Installiere mit ${green}checkinstall ... python setup.py install${NC}"
   # --spec foo -> forget the ugly spec file
-  echo -e "Installiere mit ${green}checkinstall ... python setup.py install${NC}"
   sudo checkinstall --spec foo --maintainer \""$maintainer ($maintainermail)"\" --pkglicense \""$license"\" --pkgname \""$name"\" --pkgrelease \""$release"\" --pkgversion \""$version"\" --pkgsource \""$sourceHtmlUrl"\" --pkggroup \""$group"\" --requires \""$requires"\" --pkgarch \""$architecture"\" $checkinstallParam python setup.py install
 else
+  echo
+  echog "Installiere mit ${green}checkinstall ...${NC}"
   # --spec foo -> forget the ugly spec file
-  echo -e "Installiere mit ${green}checkinstall ...${NC}"
   sudo checkinstall --spec foo --maintainer \""$maintainer ($maintainermail)"\" --pkglicense \""$license"\" --pkgname \""$name"\" --pkgrelease \""$release"\" --pkgversion \""$version"\" --pkgsource \""$sourceHtmlUrl"\" --pkggroup \""$group"\" --requires \""$requires"\" --pkgarch \""$architecture"\"
 fi
 
 exit 0
-
